//! OpenCode configuration file generation.
//!
//! Generates platform-specific files from the canonical Locus config:
//! - `opencode.json` — runtime configuration
//! - `AGENTS.md` — system prompt with Locus algorithm and skill listing
//! - `.opencode/agents/*.md` — individual agent definition files

use locus_core::adapter::GeneratedFile;
use locus_core::config::LocusConfig;
use locus_core::error::LocusError;
use locus_core::platform::Platform;

use std::path::PathBuf;

/// Generate all OpenCode configuration files from a Locus config.
pub fn generate_opencode_config(
    config: &LocusConfig,
    locus_home: &std::path::Path,
) -> Result<Vec<GeneratedFile>, LocusError> {
    let mut files = Vec::new();

    files.push(generate_opencode_json(config)?);
    files.push(generate_agents_md(locus_home)?);

    // Generate individual agent files.
    let agent_files = generate_agent_files(locus_home)?;
    files.extend(agent_files);

    Ok(files)
}

/// Generate `opencode.json` with model routing and permissions.
fn generate_opencode_json(config: &LocusConfig) -> Result<GeneratedFile, LocusError> {
    let default_model = config
        .inference
        .model
        .as_deref()
        .unwrap_or("anthropic/claude-sonnet-4-5");

    let json = serde_json::json!({
        "$schema": "https://opencode.ai/config.json",
        "model": default_model,
        "snapshot": true,
        "permission": {
            "*": "allow"
        },
        "agent": {
            "Architect": { "model": default_model },
            "Engineer": { "model": default_model },
            "Researcher": { "model": default_model },
            "Security": { "model": default_model }
        }
    });

    let content = serde_json::to_string_pretty(&json).map_err(|e| LocusError::Adapter {
        platform: Platform::OpenCode,
        message: format!("Failed to serialise opencode.json: {}", e),
    })?;

    Ok(GeneratedFile {
        path: PathBuf::from("opencode.json"),
        content,
        overwrite: false, // Don't overwrite existing user config.
    })
}

/// Generate `AGENTS.md` — the system prompt that OpenCode loads automatically.
///
/// This assembles the Locus algorithm, skill listing, and core protocols
/// into a single markdown file that OpenCode injects into every session.
fn generate_agents_md(locus_home: &std::path::Path) -> Result<GeneratedFile, LocusError> {
    let algorithm_path = locus_home.join("algorithm").join("v1.0.md");
    let algorithm_content = if algorithm_path.exists() {
        std::fs::read_to_string(&algorithm_path).unwrap_or_default()
    } else {
        "<!-- Algorithm not found. Run `locus init` to set up. -->".to_string()
    };

    // Build the skill listing from disk.
    let skills_dir = locus_home.join("skills");
    let skill_listing = build_skill_listing(&skills_dir);

    // Build the agent listing from disk.
    let agents_dir = locus_home.join("agents");
    let agent_listing = build_agent_listing(&agents_dir);

    // Read protocols.
    let degradation_path = locus_home.join("protocols").join("degradation.md");
    let degradation = if degradation_path.exists() {
        std::fs::read_to_string(&degradation_path).unwrap_or_default()
    } else {
        String::new()
    };

    let content = format!(
        r#"# Locus — Agentic Workflow Execution Framework

This file is generated by Locus. Do not edit manually.
Regenerate with: `locus platform add opencode`

---

## Algorithm

{algorithm}

---

## Available Skills

{skills}

---

## Available Agents

{agents}

---

## Degradation Protocol

{degradation}

---

## Data Directory

Locus persists learnings, research, and work artifacts to `~/.locus/data/`.
Memory schema is defined in `~/.locus/protocols/memory-schema.md`.
"#,
        algorithm = algorithm_content,
        skills = skill_listing,
        agents = agent_listing,
        degradation = degradation,
    );

    Ok(GeneratedFile {
        path: PathBuf::from("AGENTS.md"),
        content,
        overwrite: true, // AGENTS.md is always regenerated.
    })
}

/// Build a markdown listing of available skills from the skills directory.
fn build_skill_listing(skills_dir: &std::path::Path) -> String {
    if !skills_dir.exists() {
        return "No skills found. Run `locus init` to set up.".to_string();
    }

    let mut lines = Vec::new();
    lines.push("| Skill | Description | Requires Delegation |".to_string());
    lines.push("|-------|-------------|-------------------|".to_string());

    let mut entries: Vec<_> = match std::fs::read_dir(skills_dir) {
        Ok(entries) => entries.filter_map(|e| e.ok()).collect(),
        Err(_) => return "Failed to read skills directory.".to_string(),
    };
    entries.sort_by_key(|e| e.file_name());

    for entry in entries {
        let skill_md = entry.path().join("SKILL.md");
        if !skill_md.exists() {
            continue;
        }

        let content = match std::fs::read_to_string(&skill_md) {
            Ok(c) => c,
            Err(_) => continue,
        };

        let (name, description, delegation) = parse_skill_frontmatter(&content);
        let delegation_str = if delegation { "Yes" } else { "No" };
        lines.push(format!("| **{}** | {} | {} |", name, description, delegation_str));
    }

    lines.join("\n")
}

/// Parse YAML frontmatter from a SKILL.md file for the listing.
fn parse_skill_frontmatter(content: &str) -> (String, String, bool) {
    let mut name = String::from("Unknown");
    let mut description = String::new();
    let mut delegation = false;

    if !content.starts_with("---") {
        return (name, description, delegation);
    }

    if let Some(end) = content[3..].find("---") {
        let frontmatter = &content[3..3 + end];
        for line in frontmatter.lines() {
            let line = line.trim();
            if let Some(val) = line.strip_prefix("name:") {
                name = val.trim().to_string();
            } else if let Some(val) = line.strip_prefix("description:") {
                description = val.trim().to_string();
            } else if line.contains("delegation:") && line.contains("true") {
                delegation = true;
            }
        }
    }

    (name, description, delegation)
}

/// Build a markdown listing of available agents.
fn build_agent_listing(agents_dir: &std::path::Path) -> String {
    if !agents_dir.exists() {
        return "No agents found.".to_string();
    }

    let mut lines = Vec::new();
    lines.push("| Agent | Domain |".to_string());
    lines.push("|-------|--------|".to_string());

    let mut entries: Vec<_> = match std::fs::read_dir(agents_dir) {
        Ok(entries) => entries.filter_map(|e| e.ok()).collect(),
        Err(_) => return "Failed to read agents directory.".to_string(),
    };
    entries.sort_by_key(|e| e.file_name());

    for entry in entries {
        let path = entry.path();
        if path.extension().and_then(|e| e.to_str()) != Some("md") {
            continue;
        }

        let content = match std::fs::read_to_string(&path) {
            Ok(c) => c,
            Err(_) => continue,
        };

        let (name, domain) = parse_agent_frontmatter(&content);
        lines.push(format!("| **{}** | {} |", name, domain));
    }

    lines.join("\n")
}

/// Parse YAML frontmatter from an agent .md file.
fn parse_agent_frontmatter(content: &str) -> (String, String) {
    let mut name = String::from("Unknown");
    let mut domain = String::new();

    if !content.starts_with("---") {
        return (name, domain);
    }

    if let Some(end) = content[3..].find("---") {
        let frontmatter = &content[3..3 + end];
        for line in frontmatter.lines() {
            let line = line.trim();
            if let Some(val) = line.strip_prefix("name:") {
                name = val.trim().to_string();
            } else if let Some(val) = line.strip_prefix("domain:") {
                domain = val.trim().to_string();
            }
        }
    }

    (name, domain)
}

/// Generate individual agent .md files in `.opencode/agents/`.
///
/// OpenCode expects PascalCase filenames matching the agent name.
fn generate_agent_files(
    locus_home: &std::path::Path,
) -> Result<Vec<GeneratedFile>, LocusError> {
    let agents_dir = locus_home.join("agents");
    if !agents_dir.exists() {
        return Ok(Vec::new());
    }

    let mut files = Vec::new();

    let entries = std::fs::read_dir(&agents_dir).map_err(|e| LocusError::Adapter {
        platform: Platform::OpenCode,
        message: format!("Failed to read agents dir: {}", e),
    })?;

    for entry in entries.filter_map(|e| e.ok()) {
        let path = entry.path();
        if path.extension().and_then(|e| e.to_str()) != Some("md") {
            continue;
        }

        let content = std::fs::read_to_string(&path).map_err(|e| LocusError::Adapter {
            platform: Platform::OpenCode,
            message: format!("Failed to read agent file: {}", e),
        })?;

        let (name, domain) = parse_agent_frontmatter(&content);

        // OpenCode expects PascalCase filenames.
        let pascal_name = to_pascal_case(&name);

        // Generate OpenCode-format agent file with the frontmatter OpenCode expects.
        let opencode_content = format!(
            r#"---
name: {pascal_name}
description: "{domain}"
---

{content}
"#,
            pascal_name = pascal_name,
            domain = domain,
            content = content
                .find("---\n")
                .and_then(|first| content[first + 4..].find("---\n").map(|second| first + 4 + second + 4))
                .map(|body_start| content[body_start..].trim())
                .unwrap_or(""),
        );

        files.push(GeneratedFile {
            path: PathBuf::from(format!(".opencode/agents/{}.md", pascal_name)),
            content: opencode_content,
            overwrite: true,
        });
    }

    Ok(files)
}

/// Convert a name to PascalCase (e.g., "Security Specialist" -> "SecuritySpecialist").
fn to_pascal_case(s: &str) -> String {
    s.split_whitespace()
        .map(|word| {
            let mut chars = word.chars();
            match chars.next() {
                None => String::new(),
                Some(first) => {
                    let upper: String = first.to_uppercase().collect();
                    upper + &chars.as_str().to_lowercase()
                }
            }
        })
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn pascal_case_single_word() {
        assert_eq!(to_pascal_case("architect"), "Architect");
    }

    #[test]
    fn pascal_case_multi_word() {
        assert_eq!(to_pascal_case("Security Specialist"), "SecuritySpecialist");
    }

    #[test]
    fn parse_skill_frontmatter_basic() {
        let content = r#"---
id: research
name: Research
description: Comprehensive research framework.
requires:
  delegation: false
---

# Research
"#;
        let (name, desc, delegation) = parse_skill_frontmatter(content);
        assert_eq!(name, "Research");
        assert_eq!(desc, "Comprehensive research framework.");
        assert!(!delegation);
    }

    #[test]
    fn parse_skill_frontmatter_with_delegation() {
        let content = r#"---
id: council
name: Council
description: Multi-agent debate.
requires:
  delegation: true
---
"#;
        let (name, _desc, delegation) = parse_skill_frontmatter(content);
        assert_eq!(name, "Council");
        assert!(delegation);
    }
}
